import { ROOM_NAME, type ROOM_NAME_TYPE } from "./roomName";
import { ROOM_TYPE, type Room } from "./types";

export const ROOM_MAP: { [key: ROOM_NAME_TYPE]: Room } = {
	[ROOM_NAME.THE_FOUNDATION]: {
		shortName: "Fnd",
		displayName: "The Foundat-ion",
		types: [ROOM_TYPE.PERMANENT, ROOM_TYPE.BLUEPRINT],
		rarity: 4,
		doors: 5,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.ENTRANCE_HALL]: {
		shortName: "EntH",
		displayName: "Entrance Hall",
		types: [ROOM_TYPE.PERMANENT, ROOM_TYPE.BLUEPRINT],
		rarity: 0,
		doors: 6,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.SPARE_ROOM]: {
		shortName: "SprR",
		displayName: "Spare Room",
		types: [ROOM_TYPE.BLUEPRINT],
		rarity: 1,
		doors: 2,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.ROTUNDA]: {
		shortName: "Rtnd",
		displayName: "Rotunda",
		types: [ROOM_TYPE.BLUEPRINT],
		rarity: 4,
		doors: 6,
		gemCost: 3,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.PARLOR]: {
		shortName: "Par",
		displayName: "Parlor",
		types: [ROOM_TYPE.PUZZLE, ROOM_TYPE.BLUEPRINT],
		rarity: 1,
		doors: 3,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.BREAK_ROOM]: {
		shortName: "BrkR",
		displayName: "Break Room",
		types: [ROOM_TYPE.PUZZLE, ROOM_TYPE.BLUEPRINT],
		rarity: 1,
		doors: 3,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.GALLERY]: {
		shortName: "Gal",
		displayName: "Gallery",
		types: [ROOM_TYPE.PUZZLE, ROOM_TYPE.BLUEPRINT],
		rarity: 4,
		doors: 2,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.ROOM_8]: {
		shortName: "8",
		displayName: "Room 8",
		types: [ROOM_TYPE.PUZZLE, ROOM_TYPE.BLUEPRINT],
		rarity: 4,
		doors: 4,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.CLOSET]: {
		shortName: "Clst",
		displayName: "Closet",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.DEAD_END],
		rarity: 1,
		doors: 1,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.WALKIN_CLOSET]: {
		shortName: "WiC",
		displayName: "Walk–In Closet",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.DEAD_END],
		rarity: 2,
		doors: 1,
		gemCost: 1,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.ATTIC]: {
		shortName: "Att",
		displayName: "Attic",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.DEAD_END],
		rarity: 4,
		doors: 1,
		gemCost: 3,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.STOREROOM]: {
		shortName: "Str",
		displayName: "Store-room",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.DEAD_END],
		rarity: 1,
		doors: 1,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.NOOK]: {
		shortName: "Nook",
		displayName: "Nook",
		types: [ROOM_TYPE.BLUEPRINT],
		rarity: 1,
		doors: 3,
		gemCost: 0,
		gems: 0,
		keys: 1,
	},
	[ROOM_NAME.GARAGE]: {
		shortName: "Gar",
		displayName: "Garage",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.FAKE_DEAD_END],
		rarity: 3,
		doors: 1,
		gemCost: 1,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.MUSIC_ROOM]: {
		shortName: "MR",
		displayName: "Music Room",
		types: [ROOM_TYPE.BLUEPRINT],
		rarity: 3,
		doors: 3,
		gemCost: 2,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.LOCKER_ROOM]: {
		shortName: "LR",
		displayName: "Locker Room",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.SPREAD, ROOM_TYPE.ADDITION],
		rarity: 4,
		doors: 2,
		gemCost: 1,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.DEN]: {
		shortName: "Den",
		displayName: "Den",
		types: [ROOM_TYPE.BLUEPRINT],
		rarity: 1,
		doors: 5,
		gemCost: 0,
		gems: 1,
		keys: 0,
	},
	[ROOM_NAME.WINE_CELLAR]: {
		shortName: "WC",
		displayName: "Wine Cellar",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.DEAD_END],
		rarity: 3,
		doors: 1,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.TROPHY_ROOM]: {
		shortName: "TR",
		displayName: "Trophy Room",
		types: [ROOM_TYPE.BLUEPRINT],
		rarity: 4,
		doors: 3,
		gemCost: 5,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.BALLROOM]: {
		shortName: "Ball",
		displayName: "Ball-room",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.ENTRY],
		rarity: 3,
		doors: 2,
		gemCost: 2,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.PANTRY]: {
		shortName: "Pan",
		displayName: "Pantry",
		types: [ROOM_TYPE.BLUEPRINT],
		rarity: 1,
		doors: 3,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.RUMPUS_ROOM]: {
		shortName: "RR",
		displayName: "Rumpus Room",
		types: [ROOM_TYPE.BLUEPRINT],
		rarity: 2,
		doors: 2,
		gemCost: 1,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.VAULT]: {
		shortName: "Vlt",
		displayName: "Vault",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.DEAD_END],
		rarity: 4,
		doors: 1,
		gemCost: 3,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.OFFICE]: {
		shortName: "Off",
		displayName: "Office",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.SPREAD],
		rarity: 2,
		doors: 3,
		gemCost: 2,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.DRAWING_ROOM]: {
		shortName: "DR",
		displayName: "Drawing Room",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.DRAFTING],
		rarity: 1,
		doors: 5,
		gemCost: 1,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.STUDY]: {
		shortName: "Stdy",
		displayName: "Study",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.DRAFTING, ROOM_TYPE.DEAD_END],
		rarity: 3,
		doors: 1,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.LIBRARY]: {
		shortName: "Lib",
		displayName: "Library",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.DRAFTING],
		rarity: 3,
		doors: 3,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.CHAMBER_OF_MIRRORS]: {
		shortName: "CoM",
		displayName: "Chamber of Mirrors",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.DRAFTING, ROOM_TYPE.FAKE_DEAD_END],
		rarity: 3,
		doors: 6,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.THE_POOL]: {
		shortName: "Pool",
		displayName: "The Pool",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.DRAFTING],
		rarity: 1,
		doors: 5,
		gemCost: 1,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.DRAFTING_STUDIO]: {
		shortName: "DftS",
		displayName: "Drafting Studio",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.DRAFTING],
		rarity: 2,
		doors: 2,
		gemCost: 2,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.UTILITY_CLOSET]: {
		shortName: "UC",
		displayName: "Utility Closet",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.MECHANICAL, ROOM_TYPE.DEAD_END],
		rarity: 2,
		doors: 1,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.BOILER_ROOM]: {
		shortName: "BR",
		displayName: "Boiler Room",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.MECHANICAL],
		rarity: 1,
		doors: 5,
		gemCost: 1,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.PUMP_ROOM]: {
		shortName: "PR",
		displayName: "Pump Room",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.MECHANICAL, ROOM_TYPE.ADDITION],
		rarity: 3,
		doors: 3,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.SECURITY]: {
		shortName: "Sec",
		displayName: "Security",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.MECHANICAL],
		rarity: 1,
		doors: 5,
		gemCost: 1,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.WORKSHOP]: {
		shortName: "Wshp",
		displayName: "Workshop",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.MECHANICAL],
		rarity: 3,
		doors: 2,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.LABORATORY]: {
		shortName: "Lab",
		displayName: "Labora-tory",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.MECHANICAL],
		rarity: 1,
		doors: 3,
		gemCost: 1,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.SAUNA]: {
		shortName: "Sau",
		displayName: "Sauna",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.TOMORROW, ROOM_TYPE.DEAD_END, ROOM_TYPE.ADDITION],
		rarity: 3,
		doors: 1,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.COAT_CHECK]: {
		shortName: "CC",
		displayName: "Coat Check",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.TOMORROW, ROOM_TYPE.DEAD_END],
		rarity: 2,
		doors: 1,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.MAIL_ROOM]: {
		shortName: "Mail",
		displayName: "Mail Room",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.TOMORROW, ROOM_TYPE.DEAD_END],
		rarity: 3,
		doors: 1,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.FREEZER]: {
		shortName: "Free",
		displayName: "Freezer",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.TOMORROW, ROOM_TYPE.DEAD_END],
		rarity: 4,
		doors: 1,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.DINING_ROOM]: {
		shortName: "Din",
		displayName: "Dining Room",
		types: [ROOM_TYPE.BLUEPRINT],
		rarity: 2,
		doors: 5,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.OBSERVATORY]: {
		shortName: "Obs",
		displayName: "Observa-tory",
		types: [ROOM_TYPE.BLUEPRINT],
		rarity: 2,
		doors: 3,
		gemCost: 1,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.CONFERENCE_ROM]: {
		shortName: "Conf",
		displayName: "Confer-ence Rom",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.SPREAD],
		rarity: 3,
		doors: 5,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.AQUARIUM]: {
		shortName: "Aqu",
		displayName: "Aquarium",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.RED, ROOM_TYPE.GREEN, ROOM_TYPE.HALLWAY, ROOM_TYPE.BEDROOM, ROOM_TYPE.SHOP, ROOM_TYPE.BLACKPRINT],
		rarity: 3,
		doors: 5,
		gemCost: 1,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.ANTECHAMBER]: {
		shortName: "Ante",
		displayName: "Ante-chamber",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.OBJECTIVE],
		rarity: 0,
		doors: 6,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.ROOM_46]: {
		shortName: "46",
		displayName: "Room 46",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.OBJECTIVE],
		rarity: 6,
		doors: 1,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.BEDROOM]: {
		shortName: "Br",
		displayName: "Bedroom",
		types: [ROOM_TYPE.BEDROOM, ROOM_TYPE.ENTRY],
		rarity: 1,
		doors: 3,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.BOUDOIR]: {
		shortName: "Bou",
		displayName: "Boudoir",
		types: [ROOM_TYPE.BEDROOM],
		rarity: 2,
		doors: 3,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.GUEST_BEDROOM]: {
		shortName: "GBr",
		displayName: "Guest Bedroom",
		types: [ROOM_TYPE.BEDROOM, ROOM_TYPE.DEAD_END],
		rarity: 1,
		doors: 1,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.NURSERY]: {
		shortName: "Nurs",
		displayName: "Nursery",
		types: [ROOM_TYPE.BEDROOM, ROOM_TYPE.DEAD_END],
		rarity: 1,
		doors: 1,
		gemCost: 1,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.SERVANTS_QUARTERS]: {
		shortName: "Serv",
		displayName: "Servant's Quarters",
		types: [ROOM_TYPE.BEDROOM, ROOM_TYPE.DEAD_END],
		rarity: 3,
		doors: 1,
		gemCost: 1,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.BUNK_ROOM]: {
		shortName: "Bunk",
		displayName: "Bunk Room",
		types: [ROOM_TYPE.BEDROOM, ROOM_TYPE.BEDROOM, ROOM_TYPE.DEAD_END, ROOM_TYPE.DEAD_END],
		rarity: 3,
		doors: 1,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.HER_LADYSHIPS_CHAMBER]: {
		shortName: "HLC",
		displayName: "Her Ladyship's Chamber",
		types: [ROOM_TYPE.BEDROOM, ROOM_TYPE.DEAD_END],
		rarity: 4,
		doors: 1,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.MASTER_BEDROOM]: {
		shortName: "MBR",
		displayName: "Master Bedroom",
		types: [ROOM_TYPE.BEDROOM, ROOM_TYPE.DEAD_END],
		rarity: 4,
		doors: 1,
		gemCost: 2,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.HALLWAY]: {
		shortName: "Hall",
		displayName: "Hallway",
		types: [ROOM_TYPE.HALLWAY],
		rarity: 1,
		doors: 5,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.WEST_WING_HALL]: {
		shortName: "WWH",
		displayName: "West Wing Hall",
		types: [ROOM_TYPE.HALLWAY],
		rarity: 2,
		doors: 5,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.EAST_WING_HALL]: {
		shortName: "EWH",
		displayName: "East Wing Hall",
		types: [ROOM_TYPE.HALLWAY],
		rarity: 3,
		doors: 5,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.COORIDOR]: {
		shortName: "Coor",
		displayName: "Cooridor",
		types: [ROOM_TYPE.HALLWAY],
		rarity: 1,
		doors: 2,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.PASSAGEWAY]: {
		shortName: "Pass",
		displayName: "Passage-way",
		types: [ROOM_TYPE.HALLWAY],
		rarity: 1,
		doors: 6,
		gemCost: 2,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.SECRET_PASSAGE]: {
		shortName: "Secr",
		displayName: "Secret Passage",
		types: [ROOM_TYPE.HALLWAY, ROOM_TYPE.FAKE_DEAD_END],
		rarity: 3,
		doors: 2,
		gemCost: 1,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.FOYER]: {
		shortName: "Foyer",
		displayName: "Foyer",
		types: [ROOM_TYPE.HALLWAY],
		rarity: 1,
		doors: 2,
		gemCost: 2,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.GREAT_HALL]: {
		shortName: "GH",
		displayName: "Great Hall",
		types: [ROOM_TYPE.HALLWAY],
		rarity: 3,
		doors: 6,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.TERRACE]: {
		shortName: "Terr",
		displayName: "Terrace",
		types: [ROOM_TYPE.GREEN, ROOM_TYPE.DEAD_END],
		rarity: 2,
		doors: 1,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.PATIO]: {
		shortName: "Patio",
		displayName: "Patio",
		types: [ROOM_TYPE.GREEN, ROOM_TYPE.SPREAD],
		rarity: 2,
		doors: 3,
		gemCost: 1,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.COURTYARD]: {
		shortName: "Cy",
		displayName: "Court-yard",
		types: [ROOM_TYPE.GREEN],
		rarity: 1,
		doors: 5,
		gemCost: 1,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.CLOISTER]: {
		shortName: "Clois",
		displayName: "Cloister",
		types: [ROOM_TYPE.GREEN],
		rarity: 3,
		doors: 6,
		gemCost: 3,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.VERANDA]: {
		shortName: "Ver",
		displayName: "Veranda",
		types: [ROOM_TYPE.GREEN],
		rarity: 3,
		doors: 2,
		gemCost: 2,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.GREENHOUSE]: {
		shortName: "Gh",
		displayName: "Green-house",
		types: [ROOM_TYPE.GREEN],
		rarity: 2,
		doors: 3,
		gemCost: 1,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.MORNING_ROOM]: {
		shortName: "Morn",
		displayName: "Morning Room",
		types: [ROOM_TYPE.GREEN, ROOM_TYPE.TOMORROW, ROOM_TYPE.ADDITION],
		rarity: 4,
		doors: 4,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.SECRET_GARDEN]: {
		shortName: "Sec.G",
		displayName: "Secret Garden",
		types: [ROOM_TYPE.GREEN, ROOM_TYPE.SPREAD],
		rarity: 4,
		doors: 5,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.COMMISARY]: {
		shortName: "Comm",
		displayName: "Commis-ary",
		types: [ROOM_TYPE.SHOP],
		rarity: 2,
		doors: 3,
		gemCost: 1,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.KITCHEN]: {
		shortName: "Kit",
		displayName: "Kitchen",
		types: [ROOM_TYPE.SHOP],
		rarity: 1,
		doors: 3,
		gemCost: 1,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.LOCKSMITH]: {
		shortName: "Lock",
		displayName: "Lock-smith",
		types: [ROOM_TYPE.SHOP, ROOM_TYPE.DEAD_END],
		rarity: 3,
		doors: 1,
		gemCost: 1,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.SHOWROOM]: {
		shortName: "Show",
		displayName: "Showroom",
		types: [ROOM_TYPE.SHOP],
		rarity: 4,
		doors: 2,
		gemCost: 2,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.LAUNDRY_ROOM]: {
		shortName: "Laund",
		displayName: "Laundry Room",
		types: [ROOM_TYPE.SHOP, ROOM_TYPE.DEAD_END],
		rarity: 4,
		doors: 1,
		gemCost: 1,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.BOOKSHOP]: {
		shortName: "Bs",
		displayName: "Bookshop",
		types: [ROOM_TYPE.SHOP],
		rarity: 4,
		doors: 3,
		gemCost: 1,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.THE_ARMORY]: {
		shortName: "Arm",
		displayName: "The Armory",
		types: [ROOM_TYPE.SHOP, ROOM_TYPE.BLACKPRINT],
		rarity: 2,
		doors: 3,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.MOUNT_HOLLY_GIFT_SHOP]: {
		shortName: "MHGS",
		displayName: "Mount Holly Gift Shop",
		types: [ROOM_TYPE.SHOP, ROOM_TYPE.ADDITION],
		rarity: 4,
		doors: 5,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.LAVATORY]: {
		shortName: "Lav",
		displayName: "Lavatory",
		types: [ROOM_TYPE.RED, ROOM_TYPE.DEAD_END],
		rarity: 2,
		doors: 1,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.CHAPEL]: {
		shortName: "Chap",
		displayName: "Chapel",
		types: [ROOM_TYPE.RED, ROOM_TYPE.ENTRY],
		rarity: 4,
		doors: 5,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.MAIDS_CHAMBER]: {
		shortName: "Maid",
		displayName: "Maid's Chamber",
		types: [ROOM_TYPE.RED, ROOM_TYPE.BEDROOM],
		rarity: 3,
		doors: 3,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.ARCHIVES]: {
		shortName: "Arch",
		displayName: "Archives",
		types: [ROOM_TYPE.RED],
		rarity: 3,
		doors: 6,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.GYMNASIUM]: {
		shortName: "Gym",
		displayName: "Gym-nasium",
		types: [ROOM_TYPE.RED, ROOM_TYPE.ENTRY],
		rarity: 2,
		doors: 5,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.DARKROOM]: {
		shortName: "Dr",
		displayName: "Darkroom",
		types: [ROOM_TYPE.RED],
		rarity: 2,
		doors: 5,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.WEIGHT_ROOM]: {
		shortName: "WR",
		displayName: "Weight Room",
		types: [ROOM_TYPE.RED],
		rarity: 4,
		doors: 6,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.FURNACE]: {
		shortName: "Fur",
		displayName: "Furnace",
		types: [ROOM_TYPE.RED, ROOM_TYPE.DEAD_END],
		rarity: 4,
		doors: 1,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.DOVECOTE]: {
		shortName: "Dc",
		displayName: "Dovecote",
		types: [ROOM_TYPE.ADDITION, ROOM_TYPE.BLUEPRINT],
		rarity: 3,
		doors: 3,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.THE_KENNEL]: {
		shortName: "Ken",
		displayName: "The Kennel",
		types: [ROOM_TYPE.ADDITION, ROOM_TYPE.BLUEPRINT],
		rarity: 2,
		doors: 2,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.CLOCK_TOWER]: {
		shortName: "CT",
		displayName: "Clock Tower",
		types: [ROOM_TYPE.ADDITION, ROOM_TYPE.TOMORROW, ROOM_TYPE.BLUEPRINT, ROOM_TYPE.DEAD_END],
		rarity: 3,
		doors: 1,
		gemCost: 1,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.CLASSROOM]: {
		shortName: "Cr",
		displayName: "Class-room",
		types: [ROOM_TYPE.ADDITION, ROOM_TYPE.DRAFTING, ROOM_TYPE.BLUEPRINT],
		rarity: 3,
		doors: 3,
		gemCost: 1,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.SOLARIUM]: {
		shortName: "Sol",
		displayName: "Solarium",
		types: [ROOM_TYPE.ADDITION, ROOM_TYPE.GREEN, ROOM_TYPE.DEAD_END],
		rarity: 2,
		doors: 1,
		gemCost: 1,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.DORMITORY]: {
		shortName: "Dorm",
		displayName: "Dorm-itory",
		types: [ROOM_TYPE.ADDITION, ROOM_TYPE.ENTRY, ROOM_TYPE.BEDROOM, ROOM_TYPE.DEAD_END],
		rarity: 2,
		doors: 1,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.VESTIBULE]: {
		shortName: "Vest",
		displayName: "Vest-ibule",
		types: [ROOM_TYPE.ADDITION, ROOM_TYPE.HALLWAY, ROOM_TYPE.ENTRY],
		rarity: 3,
		doors: 6,
		gemCost: 2,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.CASINO]: {
		shortName: "Casi",
		displayName: "Casino",
		types: [ROOM_TYPE.ADDITION, ROOM_TYPE.SHOP],
		rarity: 3,
		doors: 3,
		gemCost: 2,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.PLANETARIUM]: {
		shortName: "Plan",
		displayName: "Planet-arium",
		types: [ROOM_TYPE.ADDITION, ROOM_TYPE.BLUEPRINT],
		rarity: 1,
		doors: 1,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.MECHANARIUM]: {
		shortName: "Mech",
		displayName: "Mech-anarium",
		types: [ROOM_TYPE.ADDITION, ROOM_TYPE.BLUEPRINT, ROOM_TYPE.MECHANICAL],
		rarity: 3,
		doors: 6,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.TREASURE_TROVE]: {
		shortName: "TT",
		displayName: "Treasure Trove",
		types: [ROOM_TYPE.ADDITION, ROOM_TYPE.BLACKPRINT],
		rarity: 3,
		doors: 3,
		gemCost: 1,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.TUNNEL]: {
		shortName: "Tunn",
		displayName: "Tunnel",
		types: [ROOM_TYPE.ADDITION, ROOM_TYPE.DRAFTING, ROOM_TYPE.HALLWAY],
		rarity: 2,
		doors: 2,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.CONSERVATORY]: {
		shortName: "Cons",
		displayName: "Conserv-atory",
		types: [ROOM_TYPE.ADDITION, ROOM_TYPE.DRAFTING, ROOM_TYPE.GREEN],
		rarity: 3,
		doors: 3,
		gemCost: 1,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.LOST_AND_FOUND]: {
		shortName: "L&F",
		displayName: "Lost & Found",
		types: [ROOM_TYPE.ADDITION, ROOM_TYPE.ENTRY, ROOM_TYPE.RED],
		rarity: 3,
		doors: 3,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.CLOSED_EXHIBIT]: {
		shortName: "CE",
		displayName: "Closed Exhibit",
		types: [ROOM_TYPE.ADDITION, ROOM_TYPE.RED],
		rarity: 1,
		doors: 5,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.THRONE_ROOM]: {
		shortName: "ThrRm",
		displayName: "Throne Room",
		types: [ROOM_TYPE.ADDITION, ROOM_TYPE.BLACKPRINT],
		rarity: 4,
		doors: 5,
		gemCost: 5,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.TOOLSHED]: {
		shortName: "Ts",
		displayName: "Toolshed",
		types: [ROOM_TYPE.OUTER_ROOM, ROOM_TYPE.BLUEPRINT, ROOM_TYPE.DEAD_END],
		rarity: 3,
		doors: 1,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.SHELTER]: {
		shortName: "Shel",
		displayName: "Shelter",
		types: [ROOM_TYPE.OUTER_ROOM, ROOM_TYPE.BLUEPRINT, ROOM_TYPE.DEAD_END],
		rarity: 3,
		doors: 1,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.SCHOOLHOUSE]: {
		shortName: "Sh",
		displayName: "School-house",
		types: [ROOM_TYPE.OUTER_ROOM, ROOM_TYPE.DRAFTING, ROOM_TYPE.DEAD_END, ROOM_TYPE.BLUEPRINT],
		rarity: 3,
		doors: 1,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.SHRINE]: {
		shortName: "Shri",
		displayName: "Shrine",
		types: [ROOM_TYPE.OUTER_ROOM, ROOM_TYPE.BLUEPRINT, ROOM_TYPE.DEAD_END],
		rarity: 3,
		doors: 1,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.ROOT_CELLAR]: {
		shortName: "RC",
		displayName: "Root Cellar",
		types: [ROOM_TYPE.OUTER_ROOM, ROOM_TYPE.GREEN, ROOM_TYPE.DEAD_END],
		rarity: 3,
		doors: 1,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.HOVEL]: {
		shortName: "Hov",
		displayName: "Hovel",
		types: [ROOM_TYPE.OUTER_ROOM, ROOM_TYPE.BEDROOM, ROOM_TYPE.DEAD_END],
		rarity: 3,
		doors: 1,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.TRADING_POST]: {
		shortName: "TP",
		displayName: "Trading Post",
		types: [ROOM_TYPE.OUTER_ROOM, ROOM_TYPE.SHOP, ROOM_TYPE.DEAD_END],
		rarity: 3,
		doors: 1,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.TOMB]: {
		shortName: "Tomb",
		displayName: "Tomb",
		types: [ROOM_TYPE.OUTER_ROOM, ROOM_TYPE.BLACKPRINT, ROOM_TYPE.DEAD_END],
		rarity: 3,
		doors: 1,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.SPARE_BEDROOM]: {
		shortName: "SprB",
		displayName: "Spare Bed-Room",
		types: [ROOM_TYPE.BEDROOM, ROOM_TYPE.UPGRADE],
		rarity: 1,
		doors: 2,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.GAME_ROOM]: {
		shortName: "Game",
		displayName: "Game Room",
		types: [ROOM_TYPE.TOMORROW, ROOM_TYPE.PUZZLE, ROOM_TYPE.BLUEPRINT, ROOM_TYPE.UPGRADE],
		rarity: 1,
		doors: 3,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.PARLOR_UPGRADE_A]: {
		shortName: "Par",
		displayName: "Parlor",
		types: [ROOM_TYPE.PUZZLE, ROOM_TYPE.BLUEPRINT, ROOM_TYPE.UPGRADE],
		rarity: 1,
		doors: 3,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.HALLWAY_CLOSET]: {
		shortName: "HallC",
		displayName: "Hall-way Closet",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.DEAD_END, ROOM_TYPE.UPGRADE],
		rarity: 1,
		doors: 1,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.STOREROOM_UPGRADE_A]: {
		shortName: "Str",
		displayName: "Store-room",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.DEAD_END, ROOM_TYPE.UPGRADE],
		rarity: 1,
		doors: 1,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.NOOK_UPGRADE_A]: {
		shortName: "Nook",
		displayName: "Nook",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.UPGRADE],
		rarity: 1,
		doors: 3,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.ELECTRIC_EEL_AQUARIUM]: {
		shortName: "EEAqu",
		displayName: "Electric Eel Aquarium",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.RED, ROOM_TYPE.GREEN, ROOM_TYPE.HALLWAY, ROOM_TYPE.BEDROOM, ROOM_TYPE.SHOP, ROOM_TYPE.BLACKPRINT, ROOM_TYPE.UPGRADE, ROOM_TYPE.MECHANICAL],
		rarity: 3,
		doors: 5,
		gemCost: 1,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.BOUDOIR_UPGRADE_A]: {
		shortName: "Bou",
		displayName: "Boudoir",
		types: [ROOM_TYPE.BEDROOM, ROOM_TYPE.UPGRADE],
		rarity: 2,
		doors: 3,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.QUEST_BEDROOM]: {
		shortName: "QstB",
		displayName: "Quest Bedroom",
		types: [ROOM_TYPE.BEDROOM, ROOM_TYPE.DEAD_END, ROOM_TYPE.UPGRADE, ROOM_TYPE.OBJECTIVE],
		rarity: 1,
		doors: 1,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.INDOOR_NURSERY]: {
		shortName: "IndN",
		displayName: "Indoor Nursery",
		types: [ROOM_TYPE.BEDROOM, ROOM_TYPE.DRAFTING, ROOM_TYPE.GREEN, ROOM_TYPE.DEAD_END, ROOM_TYPE.UPGRADE],
		rarity: 1,
		doors: 1,
		gemCost: 1,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.HALLWAY_UPGRADE_A]: {
		shortName: "Hall",
		displayName: "Hallway",
		types: [ROOM_TYPE.HALLWAY, ROOM_TYPE.UPGRADE],
		rarity: 1,
		doors: 5,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.COURTYARD_UPGRADE_A]: {
		shortName: "Cy",
		displayName: "Court-yard",
		types: [ROOM_TYPE.GREEN, ROOM_TYPE.UPGRADE],
		rarity: 1,
		doors: 5,
		gemCost: 1,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.CLOISTER_OF_DAUJA]: {
		shortName: "ClofD",
		displayName: "Cloister of Dauja",
		types: [ROOM_TYPE.GREEN, ROOM_TYPE.UPGRADE],
		rarity: 3,
		doors: 6,
		gemCost: 3,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.MAIL_ROOM_UPGRADE_A]: {
		shortName: "Mail",
		displayName: "Mail Room",
		types: [ROOM_TYPE.BLUEPRINT, ROOM_TYPE.TOMORROW, ROOM_TYPE.DEAD_END, ROOM_TYPE.UPGRADE],
		rarity: 3,
		doors: 1,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.NONE]: {
		shortName: "",
		displayName: "",
		types: [ROOM_TYPE.NONE],
		rarity: 0,
		doors: 0,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.UNPLACED]: {
		shortName: "",
		displayName: "",
		types: [ROOM_TYPE.UNPLACED],
		rarity: 0,
		doors: 0,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
	[ROOM_NAME.UNPLACED_SELECTED]: {
		shortName: "",
		displayName: "",
		types: [ROOM_TYPE.UNPLACED_SELECTED],
		rarity: 0,
		doors: 0,
		gemCost: 0,
		gems: 0,
		keys: 0,
	},
}