export const ROOM_NAME = {
	THE_FOUNDATION: "The Foundation",
	ENTRANCE_HALL: "Entrance Hall",
	SPARE_ROOM: "Spare Room",
	ROTUNDA: "Rotunda",
	PARLOR: "Parlor",
	BREAK_ROOM: "Break Room",
	GALLERY: "Gallery",
	ROOM_8: "Room 8",
	CLOSET: "Closet",
	WALKIN_CLOSET: "Walk-In Closet",
	ATTIC: "Attic",
	STOREROOM: "Storeroom",
	NOOK: "Nook",
	GARAGE: "Garage",
	MUSIC_ROOM: "Music Room",
	LOCKER_ROOM: "Locker Room",
	DEN: "Den",
	WINE_CELLAR: "Wine Cellar",
	TROPHY_ROOM: "Trophy Room",
	BALLROOM: "Ballroom",
	PANTRY: "Pantry",
	RUMPUS_ROOM: "Rumpus Room",
	VAULT: "Vault",
	OFFICE: "Office",
	DRAWING_ROOM: "Drawing Room",
	STUDY: "Study",
	LIBRARY: "Library",
	CHAMBER_OF_MIRRORS: "Chamber of Mirrors",
	THE_POOL: "The Pool",
	DRAFTING_STUDIO: "Drafting Studio",
	UTILITY_CLOSET: "Utility Closet",
	BOILER_ROOM: "Boiler Room",
	PUMP_ROOM: "Pump Room",
	SECURITY: "Security",
	WORKSHOP: "Workshop",
	LABORATORY: "Laboratory",
	SAUNA: "Sauna",
	COAT_CHECK: "Coat Check",
	MAIL_ROOM: "Mail Room",
	FREEZER: "Freezer",
	DINING_ROOM: "Dining Room",
	OBSERVATORY: "Observatory",
	CONFERENCE_ROM: "Conference Rom",
	AQUARIUM: "Aquarium",
	ANTECHAMBER: "Antechamber",
	ROOM_46: "Room 46",
	BEDROOM: "Bedroom",
	BOUDOIR: "Boudoir",
	GUEST_BEDROOM: "Guest Bedroom",
	NURSERY: "Nursery",
	SERVANTS_QUARTERS: "Servant's Quarters",
	BUNK_ROOM: "Bunk Room",
	HER_LADYSHIPS_CHAMBER: "Her Ladyship's Chamber",
	MASTER_BEDROOM: "Master Bedroom",
	HALLWAY: "Hallway",
	WEST_WING_HALL: "West Wing Hall",
	EAST_WING_HALL: "East Wing Hall",
	COORIDOR: "Cooridor",
	PASSAGEWAY: "Passageway",
	SECRET_PASSAGE: "Secret Passage",
	FOYER: "Foyer",
	GREAT_HALL: "Great Hall",
	TERRACE: "Terrace",
	PATIO: "Patio",
	COURTYARD: "Courtyard",
	CLOISTER: "Cloister",
	VERANDA: "Veranda",
	GREENHOUSE: "Greenhouse",
	MORNING_ROOM: "Morning Room",
	SECRET_GARDEN: "Secret Garden",
	COMMISARY: "Commisary",
	KITCHEN: "Kitchen",
	LOCKSMITH: "Locksmith",
	SHOWROOM: "Showroom",
	LAUNDRY_ROOM: "Laundry Room",
	BOOKSHOP: "Bookshop",
	THE_ARMORY: "The Armory",
	MOUNT_HOLLY_GIFT_SHOP: "Mount Holly Gift Shop",
	LAVATORY: "Lavatory",
	CHAPEL: "Chapel",
	MAIDS_CHAMBER: "Maid's Chamber",
	ARCHIVES: "Archives",
	GYMNASIUM: "Gymnasium",
	DARKROOM: "Darkroom",
	WEIGHT_ROOM: "Weight Room",
	FURNACE: "Furnace",
	DOVECOTE: "Dovecote",
	THE_KENNEL: "The Kennel",
	CLOCK_TOWER: "Clock Tower",
	CLASSROOM: "Classroom",
	SOLARIUM: "Solarium",
	DORMITORY: "Dormitory",
	VESTIBULE: "Vestibule",
	CASINO: "Casino",
	PLANETARIUM: "Planetarium",
	MECHANARIUM: "Mechanarium",
	TREASURE_TROVE: "Treasure Trove",
	TUNNEL: "Tunnel",
	CONSERVATORY: "Conservatory",
	LOST_AND_FOUND: "Lost And Found",
	CLOSED_EXHIBIT: "Closed Exhibit",
	THRONE_ROOM: "Throne Room",
	TOOLSHED: "Toolshed",
	SHELTER: "Shelter",
	SCHOOLHOUSE: "Schoolhouse",
	SHRINE: "Shrine",
	ROOT_CELLAR: "Root Cellar",
	HOVEL: "Hovel",
	TRADING_POST: "Trading Post",
	TOMB: "Tomb",
	SPARE_BEDROOM: "Spare Bedroom",
	GAME_ROOM: "Game Room",
	PARLOR_UPGRADE_A: "Parlor Upgrade A",
	HALLWAY_CLOSET: "Hallway Closet",
	STOREROOM_UPGRADE_A: "Storeroom Upgrade A",
	NOOK_UPGRADE_A: "Nook Upgrade A",
	ELECTRIC_EEL_AQUARIUM: "Electric Eel Aquarium",
	BOUDOIR_UPGRADE_A: "Boudoir Upgrade A",
	QUEST_BEDROOM: "Quest Bedroom",
	INDOOR_NURSERY: "Indoor Nursery",
	HALLWAY_UPGRADE_A: "Hallway Upgrade A",
	COURTYARD_UPGRADE_A: "Courtyard Upgrade A",
	CLOISTER_OF_DAUJA: "Cloister of Dauja",
	MAIL_ROOM_UPGRADE_A: "Mail Room Upgrade A",
	NONE: "None",
	UNPLACED: "Unplaced",
	UNPLACED_SELECTED: "Unplaced Selected",
}

export type ROOM_NAME_TYPE = typeof ROOM_NAME[keyof typeof ROOM_NAME];